# Welcome to yourown-bootstrap4!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically.

# Site settings
title: edu
email: k.olszewski@o2.pl
description: > # this means to ignore newlines until "github_username:"
  Edukacja
github_username: kolszewskieu

# Build settings
markdown: kramdown

# Settings specific to Zee
#zee_google_analytics: "" 
#zee_crisp_im: "" 


# Exclude nodes artifacts from build
exclude:
  - package.json
  - fonts.list
  - npm-debug.log
  - node_modules
  - gulpfile.js
  